Repository stolostron/hypershift-addon-operator, pull requests merged in 2022-11, with the labels that each got.

#96 fix ACM-1923 so that addon restart does not reinstall the hypershift …
  pkg/agent/agent.go
  pkg/install/hypershift.go
  pkg/install/hypershift_test.go
  pkg/install/upgrade.go
  pkg/util/constant.go
Labels: approved

#97 Add new addon status controller to check and set status based on Hypershift deployments statuses
  hack/crds/managedclusteraddons.crd.yaml
  pkg/agent/addon_status_controller.go
  pkg/agent/addon_status_controller_test.go
  pkg/agent/addon_status_helper.go
  pkg/agent/addon_status_helper_test.go
  pkg/agent/agent.go
  pkg/agent/suite_test.go
  pkg/manager/manifests/permission/role.yaml
  pkg/util/constant.go
  test/e2e/install_test.go
Labels: approved, lgtm

#100 fix doc error for hypershift hosted cluster on mce
  docs/provision_hosted_cluster_on_mce_local_cluster.md
Labels: approved, lgtm, needs-ok-to-test

#103 fix incorrect usage of controllerutil.CreateOrUpdate()
  pkg/install/hypershift.go
  pkg/install/hypershift_test.go
Labels: approved, lgtm, ok-to-test

#104 ACM-2052: fix the external DNS doc
  docs/provision_hosted_cluster_on_mce_local_cluster.md
Labels: approved

#106 Update the manifestwork HC doc
  docs/provision_hypershift_clusters_by_manifestwork.md
Labels: approved

#107 Use the addon image pull secret for the install job
  pkg/install/install_job.go
Labels: approved, lgtm

#111 ACM-1754: enable hypershift-addon on local-cluster automatically
  docs/provision_hosted_cluster_on_mce_local_cluster.md
Labels: approved, lgtm

#115 AddOnPlacementScore condition and clusterClaim for max HC count
  docs/scheduling_hosted_cluster.md
  pkg/agent/agent.go
  pkg/agent/agent_test.go
  pkg/agent/clusterclaim.go
  pkg/util/constant.go
Labels: approved, lgtm

#113 Support node selector and tolerations
  go.mod
  go.sum
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/manifests/templates/clusterrole.yaml
  pkg/manager/manifests/templates/deployment.yaml
Labels: approved, lgtm

#116 add more doc on AddOnPlacementScore
  docs/scheduling_hosted_cluster.md
Labels: approved

#117 Add a doc to explain the hypershift addon status in details.
  docs/hypershift_addon_status.md
Labels: approved, lgtm

#110 Switch the default ManagedCluster name from InfraID to HostedCluster.…
  pkg/agent/agent.go
  pkg/agent/agent_test.go
Labels: approved, lgtm
